# path
checkpoints: ./checkpoint/TEST/model_00000002.pt

# data
# data_root: ./data/LINEMOD
# class:
#   - 'ape'
#   - 'cat'
#   - 'iron'
data_root: ./data/TEST
class:
  - 'diffuser'
  - 'realsense'
  - 'peace'
img_size: 672

# log frequency
log_freq: 2
checkpoint_freq: 3

# training
batch_size: 1
num_workers: 1
max_epochs: 1

# optimizer
lr: 0.0001
beta1: 0.5
beta2: 0.999
eps: 0.00000001 

# network
rgb_2_vf_seg:
  n_f: 8
  n_down: 3
  n_res_blks: 2

bb_net:
  n_f: 8
  n_updown: 3
  n_res_blks: 2