# path
checkpoint: ./checkpoint/train5/model_00080000.pt

# data
data_root: ./data/LINEMOD
n_class: 13

# data_root: ./data/TEST
# n_class: 3
img_size: 672

# log frequency
log_freq: 100
checkpoint_freq: 1000

# training
batch_size: 8
num_workers: 4
max_epochs: 100

# optimizer
lr: 0.0001
beta1: 0.5
beta2: 0.999
eps: 0.00000001

# loss weights & paramters
cf_w: 1
pt_w: 1
vf_w: 1
sg_w: 1
cl_w: 1

sigma: 0.4

# network
rgb_2_vf_seg:
  n_f: 8
  n_down: 3
  n_res_blks: 2

mlp:
  n_f: 8
  n_blks: 3

cf_net:
  n_f: 8
  n_updown: 3
  n_res_blks: 2

# test
k: 10 # k-samples for hough voting